import { ImageContainer } from "@/app/_components/imageContainer";
import { LinkWithIcon } from "@/app/_components/linkWithIcon";

export default function Page() {
    return (
        <>
            <div className="page">
                <h1>Harmonograph</h1>
                <p>
                    I first learnt about harmonographs when I was about 12 years
                    old. Essentially, they're mechanisms that are made up of a
                    number of pendulums (2 or 3) that move independently in
                    different axes, and their position is then added up to
                    produce a path. The images that form from simply adding
                    harmonic motion together can be quite stunning, so naturally
                    I wanted to build one. Unfortunately, I was never able to
                    make a physical harmonograph, so I eventually decided to
                    make a harmonograph in Desmos.
                </p>
                <p>
                    This is one of my most annotated and explained graphs, at
                    least in terms of the input.
                </p>
                <p>Link:</p>
                <LinkWithIcon
                    href="https://www.desmos.com/calculator/875211cd3d"
                    src="/Icons/desmos.ico"
                    target="_blank"
                >
                    Desmos harmonograph
                </LinkWithIcon>
                <p>And here are some images of what it can produce:</p>
                <ImageContainer caption="Some examples of shapes generated by my Desmos harmonograph.">
                    <img src="/Images/h0.png" />
                    <img src="/Images/h1.png" />
                    <img src="/Images/h2.png" />
                </ImageContainer>
            </div>
        </>
    );
}
