<section>
    <h1>AI statement</h1>
    <p>
        This is meant to be a general file describing when and how I use generative
        AI when making my programs. I link to it from various other projects, and it
        serves as a central policy of sorts.
    </p>
    <h2>When do I use generative AI?</h2>
    <p>
        I don't use any assets generated by LLMs as part of my final projects. This
        includes images, videos, code, text and any other forms of content.
    </p>
    <p>
        I do use chatbots sometimes when I'm stuck on a problem and searching the
        internet has failed to give results. Most of these times the LLM gives the
        wrong answer too, but the discussion still often gives me the insight needed
        to solve the issue. If the chatbot generates a "sample" asset, like an
        example function or a draft of a paragraph, I completely ignore that and
        create my own version instead. This guarantees both that I know what's
        happening, and that I know what has gone into my project.
    </p>
    <p>
        I also occasionally use them for early feedback on designs, important pieces
        of text etc, but I never accept rewrites; I just ask for opinions and then
        follow the ones I agree with. I do my best to keep my own soul and style
        showing through.
    </p>
    <p>
        The exception to this policy would be if I do a project where an LLM is the
        main focus. For example, a project where I host a small home-trained LLM
        myself; of course that project would contain LLM-generated data. But then the
        generated data will be clearly marked as such, and the "supporting" assets
        would still be my own.
    </p>
</section>
